### ISSUE TITLE
fasmg executable missing 

### ISSUE THREAD

**Issue by catafest** [mikegonta/fasmg.x86#1]
I don't find fasmg from bat file:
`set include=include
fasmg hello.asm hello.com
fasmg life.asm life.com
fasmg mandel.asm mandel.com
fasmg multiseg.asm multiseg.exe
fasmg usedpmi.asm usedpmi.exe
fasmg win32.asm win32.exe
fasmg win64.asm win64.exe
fasmg win64avx.asm win64avx.exe 
`

**Comment by mikegonta** [comment]
This is a source only distribution with some additions (I'm still working on the rest).
The original can be downloaded at http://flatassembler.net/download.php
